---
- hosts: default
  name: default
  become: true

  tasks:
  - name: write /etc/hosts
    copy:
      src: hostsfile
      dest: /etc/hosts
    tags: files

  - name: write /etc/yum.conf
    copy:
      src: yum.conf
      dest: /etc/yum.conf
    tags: files

  - shell: rpm -Uvh http://repos.mesosphere.com/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm
    ignore_errors: true

  - shell: rpm -Uvh http://archive.cloudera.com/cdh4/one-click-install/redhat/6/x86_64/cloudera-cdh-4-0.x86_64.rpm
    ignore_errors: true

  - name: Install java
    yum:
      name: java-1.8.0-openjdk.x86_64
      state: latest

  - name: Install docker
    yum:
      name: docker
      state: latest
  
  - name: Install mesos
    yum: 
      name: mesos
      state: latest
    
  - name: Install marathon
    yum: 
      name: marathon
      state: latest

  - name: Install zookeeper
    yum: 
      name: zookeeper
      state: latest
  
  - name: Install zookeeper-server
    yum: 
      name: zookeeper-server
      state: latest

  - shell: zookeeper-server-initialize --myid=1 --force
    become_user: zookeeper

  - name: Start zookeeper-server
    service: 
      name: zookeeper-server
      state: started
      enabled: yes  

  - name: Start mesos-master
    service: 
      name: mesos-master
      state: started
      enabled: yes  

  - name: write /etc/mesos-slave/containerizers
    copy:
      src: mesos-slave-containerizers
      dest: /etc/mesos-slave/containerizers
    tags: files

  - name: Start mesos-slave
    service: 
      name: mesos-slave
      state: started
      enabled: yes

  - name: write /etc/default/marathon
    copy:
      src: marathon_conf
      dest: /etc/default/marathon
    tags: files

  - name: Start docker
    service: 
      name: docker
      state: started
      enabled: yes  

  - name: Start marathon
    service: 
      name: marathon
      state: started
      enabled: yes  
